### ISSUE TITLE
Users not Saved

### ISSUE THREAD

**Issue by phil568622** [weaondara/BungeePermsBukkit#2]
Ive got a problem with bungeeperms.

Im using it with MySQL backend configured properly, and 1 install in bungeecord and on 1 server with bungeepermsbukkit. Now when i join, there is a message that default permissions were added to me. Now i give me * via console, but after rejoining the bungee, all my permissions are lost and im default again.

**Comment by weaondara** [comment]
please use the mysql2 backend for permissions
and the mysql backend for uuidplayerdb
