### ISSUE TITLE
Commands not available from Bukkit/Spigot server console

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePermsBukkit#3]
The plugin is running fine, but it seems the commands aren't registered on the Bukkit console. They work from both the BungeeCord console and a connected MC client to the server instance, so the plugin appears to be running.

**Comment by weaondara** [comment]
currently any modification can only be done at bungeecord
but i planned to make commands also available to the backend servers of bungee networks

**Comment by weaondara** [comment]
i move this to bungee part of bungeeperms
