### ISSUE TITLE
Problems with Vault

### ISSUE THREAD

**Issue by phil568622** [weaondara/BungeePermsBukkit#5]
Hey weaondara, i just wanted to know if your plugin is vault compatible...

because i cant get prefixes to work

**Comment by tuxillator** [comment]
What vault-compatible chat plugin are you using to add the prefix?

**Comment by phil568622** [comment]
I tried essentialschat, simpleprefix and a bungeecord based chat manager. I tried it using vault for 1.8

**Comment by tuxillator** [comment]
This plugin doesn't have the vault integration built-in, you'll need the BungeePermsBukkitBridge plugin as well to add the chat prefixes. If that works can you close this issue?

**Comment by phil568622** [comment]
Bungeeperms Bukkit Bridge IS installed...

**Comment by tuxillator** [comment]
2 questions:
- Do you see some form of "vault hooked" message in your logs? (attach the vault/chat/bungeeperms related logs here)
- Which chat plugin are you using?
My (working) setup looks like this:

---
BungeeCord plugins:
- BungeePerms

Spigot plugins:
- BungeePermsBukkit
- BungeePermsBukkitBridge
- Vault
- Vault-compatible chat plugin supporting chat prefixes

---
On a related note, while this plugin is not "officially supported" by Vault, it works fine as the author uses reflection to inject into Vault. I'd be happy to write a pull requests to Vault and here to formalise support but am waiting to see if BungeePerms accepts pull requests before I invest effort.

**Comment by phil568622** [comment]
Im gona setup a test Server today

**Comment by phil568622** [comment]
Update:

Test Server is running with BungeePermsBukkit, Vault and SimplePrefix.

I cant find any "hooked with vault" message.

Logs:  http://pastebin.com/pJJU9eTd

**Comment by tuxillator** [comment]
Which chat plugin are you using?

**Comment by tuxillator** [comment]
Oh... SimplePrefix (let me check)

**Comment by phil568622** [comment]
I tried it with ChatEX and Essentials Chat too, I think thats not the Problem.

**Comment by tuxillator** [comment]
There's this: http://dev.bukkit.org/bukkit-plugins/simple-prefix/
> SimplePrefix may not work in offline mode, and I'm not planning to make it so any time soon. No support will be offered to offline mode servers

However I agree with you. When I was using this, I saw this message in the logs at startup (and it's reflected in the source code too):
```
[BungeePermsBukkitBridge] Injection of BungeepermsBukkit into Vault
```

The code is very simple... the only branch of interest before this is checking if Vault is present:
```
Plugin plugin = Bukkit.getPluginManager().getPlugin("Vault");
if(plugin!=null) {
  inject(plugin);
}
```

You definitely have the BungeePermsBukkitBridge plugin installed properly? Where did you download it from?

**Comment by phil568622** [comment]
I habe downloaded it from spigotmc.org, the file was a ZIP with bungeeperms.jar and bungeepermsbukkit.jar. I'll download the newest Version...

**Comment by phil568622** [comment]
Oh, i think i have only installed BungeePermsBukkit. Whats the difference between bungeepermsbukkit and the bridge?!?!

**Comment by phil568622** [comment]
Installed BungeePermsBukkitBridge, re-installed SimplePrefix (it has a Bungeecord Option - for offline mode). I can add the Prefixes manually with SimplePrefix, that works. I can also set a prefix for a group, but then it doesnt shows me the prefix. do i need to enable sth. in the BungeePermsBukkit or BungeePerms config?

**Comment by tuxillator** [comment]
> Whats the difference between bungeepermsbukkit and the bridge?!?!

You probably figured it out, but for the sake of Google: the bridge seems to be for holding hook code to other APIs, e.g. Vault, WorldGuard, etc. I feel this should exist in the BungeePerms plugin instead but that's the way it's implemented at the moment.

> do i need to enable sth. in the BungeePermsBukkit or BungeePerms config?

I don't think so... I just dropped a chat plugin in and it worked out of the box. Perhaps double-check the group prefix is applied properly with `bp group <groupname> info`? Also may want to try a different Vault compatible plugin for sanity's sake.

**Comment by phil568622** [comment]
Okay, i still dont get it to work. What chat Plugin are you using? 

/bp group Group info gives me the output that the Prefix is set properly... 

Could you maybe give me your config without MySQL settings - i think i did something wrong with the options

**Comment by phil568622** [comment]
UPDATE:

Still trying to get it to work... Looked into mysql manually via heidisql, the prefix is set properly. 
Im getting desperated....

**Comment by weaondara** [comment]
ok i tested essentials chat just some hours ago ... i think i need to take another look at vault compat ...

**Comment by phil568622** [comment]
OK, where can i get the newest Version of BungeePermsBukkitBridge? Because I downloaded it from the Website, but its a old Version...

**Comment by phil568622** [comment]
weaondara, its great to see you alive!

**Comment by weaondara** [comment]
:D i'm sry for not responding continuously but as long as "my" server is active bungeeperms will be developed

reguarding essentials chat: it seems not to be vault dependend ... it has its own adapters

**Comment by phil568622** [comment]
Okay, thats good to hear ;)

Could you maybe add a Version oft BungeePermsBukkitBridge into the ZIP on spigotmc.org? I think many issues result in not installing the Bridge... And could you please give us a updates Version of BungeePermsBukkitBridge? 

And, im trying to get FreeBungeeChat working with BungeePerms. It has its own Bridge Plugin, but that doesnt work right. What about adding direct Support of FreeBungeeChat? Would be very very nice ;)

Thanks,
Philip Ziegler

**Comment by weaondara** [comment]
i'll add a version tomorrow or the day after ... i'm tired for now and it's still not working
sry for any inconvinience

**Comment by phil568622** [comment]
weaondara, what about working together with tuxillator on adding Vault support an Bug Fixes? I think he could help ;)

**Comment by weaondara** [comment]
ok done ... dev build on bungeeperms page on spigotmc.org

**Comment by phil568622** [comment]
Yeah, IT WORKS!

I can see this message on console:

[11:35:58] [Server thread/INFO]: [Vault] [Chat] BungeePermsBukkit found: Loaded

Very nice! Thanks!

**Comment by weaondara** [comment]
ok -> close
