### ISSUE TITLE
Permission Groups not recognized

### ISSUE THREAD

**Issue by skeptibat** [weaondara/BungeePermsBukkit#6]
Not sure if this is a BukkitBridge issue or not, but I'm using the BungeeSuiteChat plugin, and it claims that the permissions group:
     bungeesuite.chat.user

Contains the children permissions:
     bungeesuite.chat.channel.server
     bungeesuite.chat.channel.local

And a few others.

Giving permission "bungeesuite.chat.channel.server" works fine but giving the permission " bungeesuite.chat.user" does not.

I'm using version 2.5 of BungeePerms, BungeePermsBukkit, and BungeePermsBukkitBridge
Apologies if this isn't a BungePermsBukkit bug.

**Comment by weaondara** [comment]
thx for report

note for wea_ondara: allow child perms when superpermscompat

**Comment by weaondara** [comment]
fixed in bp 3.0
