### ISSUE TITLE
Access the prefix from bungeeperms

### ISSUE THREAD

**Issue by mechoriet** [weaondara/BungeePermsBukkit#7]
how can i access Bungeeperms prefix from bukkit`s side
example.

**Comment by weaondara** [comment]
you can use vault or access bungeepermsbukkit directly
examples will follow

**Comment by yolomaker** [comment]
hope you have some kind of api,
i can use to access it from java.
should be awsome

**Comment by weaondara** [comment]
of course, there is
for short:
- the permissions manager is the main class handling permissions (getPermissionsManager() in BungeePerms (plugin class))
- user and group objcets can be obtained from permissions manager; they contain prefix, suffix, ...

**Comment by weaondara** [comment]
example
https://github.com/weaondara/BungeePermsBukkit/blob/master/src/main/java/net/alpenblock/bungeeperms/bukkit/bridge/bridges/vault/Chat_BungeePermsBukkit.java#L89

**Comment by tuxillator** [comment]
+1 vote for just using Vault. @weaondara has already moved the functionality into this plugin with the latest build and formal support looks close. Once you implement Vault you can use their API to get the prefix.

**Comment by yolomaker** [comment]
is there also a way to set / add a group to a player from bukkit side?
dunno if its possible to add/create a plugin channel to transfer it over to the core it self

**Comment by weaondara** [comment]
bp 3.0 will support that .. also via vault
but it will take sometime until bp 3.0 will be stable
